### ISSUE TITLE
Tutorial of Running Code on Replit

### ISSUE THREAD

**Issue by Neme-sys-IO** [Ryuji-Ly/Asir#1]
I would like to request guidance on how to run code on Replit. I'm currently facing some challenges and would appreciate some assistance and documentation on the process. 

**Steps to Reproduce:**
- Attempt to run code on Replit.
- Encounter difficulties or uncertainties during the process.

**Expected Behavior:**
I would like to understand the correct steps and best practices for running code on Replit without issues.

**Additional Information:**
Any information, guides, or resources you can provide on how to effectively run code on Replit would be greatly appreciated. Thank you for your assistance.

**Labels:**
- help wanted
- documentation

**Comment by Ryuji-Ly** [comment]
Running code on Replit should be simple, however to my knowledge it can't handle things if the number of files and size gets too big, if you are trying to run this repository on replit, there's lots of limitations as well, for smaller projects using replit to host the entire project on the cloud is the best choice, but it you want something with large amounts of commands, and something like a dashboard, you will have to move away from that.
You will also need a .env file with your bot token, as well as mongodb key

If it is your first time creating a discord bot, try making one without a dashboard, take things one step at a time, make it respond to a command, have various commands, connect the bot to a database, interact with the database with the bot, after you are comfortable with that, then try making a dashboard.
Personally it is my first time making a bot with a dashboard myself, and I consider myself fairly novice at programming, so not sure if I can help much.
As for documentation I am planning on adding that after checking that everything works as it is still a work in progress
